In [129]:
%pip install picsure

Requirement already satisfied: picsure in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (2.0.1.dev12+gbe25f15e1)
Requirement already satisfied: httpx<1,>=0.27 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from picsure) (0.28.1)
Requirement already satisfied: pandas<3,>=2 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from picsure) (2.3.3)
Requirement already satisfied: fastavro>=1.12.1 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from picsure) (1.12.2)
Requirement already satisfied: httpcore==1.* in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from httpx<1,>=0.27->picsure) (1.0.9)
Requirement already satisfied: idna in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from httpx<1,>=0.27->picsure) (3.20)
Requirement already satisfied: certifi in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from httpx<1,>=0.27->picsure) (2026.7.22)
Requirement already satisfied: anyio in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from httpx<1,>=0.27->picsure) (4.15.1)
Requirement already satisfied: h11>=0.16 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.27->picsure) (0.16.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from pandas<3,>=2->picsure) (2.2.6)
Requirement already satisfied: tzdata>=2022.7 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from pandas<3,>=2->picsure) (2026.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from pandas<3,>=2->picsure) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from pandas<3,>=2->picsure) (2026.3.post1)
Requirement already satisfied: six>=1.5 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas<3,>=2->picsure) (1.17.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from anyio->httpx<1,>=0.27->picsure) (1.3.1)
Requirement already satisfied: typing_extensions>=4.16.0 in /Users/michael/.pyenv/versions/3.10.20/lib/python3.10/site-packages (from anyio->httpx<1,>=0.27->picsure) (4.16.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [130]:
import sys
import pandas as pd
import picsure

In [ ]:
!{sys.executable} -m pip install --upgrade --force-reinstall git+https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git@main

Collecting git+https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git@review-fixes-2026-09-10
  Cloning https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git (to revision review-fixes-2026-09-10) to /private/var/folders/p_/ym6860hj3tb2c4d9gm12knxh0000gp/T/pip-req-build-b902967u
  Running command git clone --filter=blob:none --quiet https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git /private/var/folders/p_/ym6860hj3tb2c4d9gm12knxh0000gp/T/pip-req-build-b902967u
  Running command git checkout -b review-fixes-2026-09-10 --track origin/review-fixes-2026-09-10
  Switched to a new branch 'review-fixes-2026-09-10'
  branch 'review-fixes-2026-09-10' set up to track 'origin/review-fixes-2026-09-10'.
  Resolved https://github.com/hms-dbmi/pic-sure-python-adapter-hpds.git to commit be25f15e15c871f9215fa673372f767229651065
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting fastavro>=1.12.1
  Using cached fastavro-1.12.2-cp310-cp310-macosx_10_9_universal2.whl (976 kB)
Collecting httpx<1,>=0.27
  Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Collecting pandas<3,>=2
  Using cached pandas-2.3.3-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
Collecting idna
  Downloading idna-3.20-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.6/69.6 kB 1.4 MB/s eta 0:00:00a 0:00:01
Collecting certifi
  Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
Collecting anyio
  Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.1/132.1 kB 2.7 MB/s eta 0:00:00a 0:00:01
Collecting httpcore==1.*
  Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Collecting h11>=0.16
  Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Collecting tzdata>=2022.7
  Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.5/347.5 kB 3.9 MB/s eta 0:00:00a 0:00:01
Collecting pytz>=2020.1
  Using cached pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Collecting numpy>=1.22.4
  Using cached numpy-2.2.6-cp310-cp310-macosx_14_0_arm64.whl (5.3 MB)
Collecting six>=1.5
  Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Collecting typing_extensions>=4.16.0
  Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Collecting exceptiongroup>=1.0.2
  Using cached exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Building wheels for collected packages: picsure
  Building wheel for picsure (pyproject.toml) ... done
  Created wheel for picsure: filename=picsure-2.0.1.dev12+gbe25f15e1-py3-none-any.whl size=97268 sha256=d010b9365f33f75bd1cbb42e885c6b2c1232f4295044ca663a7fb4734bc371fa
  Stored in directory: /private/var/folders/p_/ym6860hj3tb2c4d9gm12knxh0000gp/T/pip-ephem-wheel-cache-4tbm76me/wheels/b8/11/c1/b21aa3089ff1d069244e71f8b73887f11b8758394d3fe33d57
Successfully built picsure
Installing collected packages: pytz, tzdata, typing_extensions, six, numpy, idna, h11, fastavro, certifi, python-dateutil, httpcore, exceptiongroup, pandas, anyio, httpx, picsure
  Attempting uninstall: pytz
    Found existing installation: pytz 2026.3.post1
    Uninstalling pytz-2026.3.post1:
      Successfully uninstalled pytz-2026.3.post1
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2026.3
    Uninstalling tzdata-2026.3:
      Successfully uninstalled tzdata-2026.3
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6
  Attempting uninstall: idna
    Found existing installation: idna 3.18
    Uninstalling idna-3.18:
      Successfully uninstalled idna-3.18
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: fastavro
    Found existing installation: fastavro 1.12.2
    Uninstalling fastavro-1.12.2:
      Successfully uninstalled fastavro-1.12.2
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.7.22
    Uninstalling certifi-2026.7.22:
      Successfully uninstalled certifi-2026.7.22
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: httpcore
    Found existing installation: httpcore 1.0.9
    Uninstalling httpcore-1.0.9:
      Successfully uninstalled httpcore-1.0.9
  Attempting uninstall: exceptiongroup
    Found existing installation: exceptiongroup 1.3.1
    Uninstalling exceptiongroup-1.3.1:
      Successfully uninstalled exceptiongroup-1.3.1
  Attempting uninstall: pandas
    Found existing installation: pandas 2.3.3
    Uninstalling pandas-2.3.3:
      Successfully uninstalled pandas-2.3.3
  Attempting uninstall: anyio
    Found existing installation: anyio 4.14.2
    Uninstalling anyio-4.14.2:
      Successfully uninstalled anyio-4.14.2
  Attempting uninstall: httpx
    Found existing installation: httpx 0.28.1
    Uninstalling httpx-0.28.1:
      Successfully uninstalled httpx-0.28.1
  Attempting uninstall: picsure
    Found existing installation: picsure 2.0.0
    Uninstalling picsure-2.0.0:
      Successfully uninstalled picsure-2.0.0
Successfully installed anyio-4.15.1 certifi-2026.7.22 exceptiongroup-1.3.1 fastavro-1.12.2 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 idna-3.20 numpy-2.2.6 pandas-2.3.3 picsure-2.0.1.dev12+gbe25f15e1 python-dateutil-2.9.0.post0 pytz-2026.3.post1 six-1.17.0 typing_extensions-4.16.0 tzdata-2026.4

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [131]:
token_file = "token.txt"

try:
    with open(token_file, "r") as f:
        my_token = f.read().strip()
    print(f"Token loaded from {token_file}")
except FileNotFoundError:
    raise FileNotFoundError(
        f"No {token_file} found in this directory."
    )

Token loaded from token.txt

In [133]:
session = picsure.connect(picsure.Platform.BDC_OPEN, my_token)

PicSureConnectionError: Connected to BDC Open but could not fetch resources. The server may be temporarily unavailable.

In [116]:
token_file = "token.txt"

with open(token_file, "r") as f:
    my_token = f.read()

session = picsure.connect(picsure.Platform.BDC_AUTHORIZED, my_token)

PicSureConnectionError: Connected to BDC Authorized but could not fetch resources. The server may be temporarily unavailable.

In [100]:
session.getResourceID()

Empty DataFrame
Columns: [uuid, name, description]
Index: []

In [42]:
newid = session.searchDictionary("newid")
new_id = session.searchDictionary("new_id")
samp_id = session.searchDictionary("samp_id")
sampid = session.searchDictionary("sampid")
randid = session.searchDictionary("randid")
rand_id = session.searchDictionary("rand_id")
marriage = session.searchDictionary("marriage")
herpesvirus = session.searchDictionary("herpesvirus")
cocaine = session.searchDictionary("cocaine")

In [77]:
herpesvirus = session.searchDictionary("herpesvirus")
herpesvirus['conceptPath'][0]

'\\phs003463\\RECOVER_adult\\EHR\\DrugExposure\\ACT\\Medications\\MedicationsByAlpha\\V2_12112018\\RxNormUMLSRxNav\\HPreparations\\11131\\herpesvirus 3, human(S-507832)\\'

In [80]:
age = session.searchDictionary("age")

In [83]:
age_spiro = age[age['studyId']=="phs001119"]
age_spiro
age_spiro.to_csv('test.csv', index=False)

In [87]:
apnea = session.searchDictionary("apnea")
apnea_rec = apnea[apnea['studyId']=="phs003463"]
apnea_rec.to_csv('test.csv', index=False)

In [88]:
lt = session.searchDictionary("long-term")
lt_rec = lt[lt['studyId']=="phs003463"]
lt_rec.to_csv('test.csv', index=False)

In [78]:
sampid = session.searchDictionary("sample id")
sampid

,conceptPath,name,display,description,dataType,studyId,values,min,max,allowFiltering,meta,studyAcronym
0,\phs000335\pht002116\phv00154555\sample1\,phv00154555,sample1,First sample ID of cryptic relatedness,Continuous,phs000335,[],267718.0,577777.0,True,None,HF_Collection_LHS
1,\phs001013\pht005310\phv00259372\SUBJECT_ID\,phv00259372,SUBJECT_ID,Subject ID,Continuous,phs001013,[],100001.0,101199.0,False,None,HVH
2,\phs001013\pht005310\phv00259373\SAMPLE_ID\,phv00259373,SAMPLE_ID,Sample ID,Categorical,phs001013,"[S10001, S10002, S10003, S10004, S10005, S1000...",NaN,NaN,False,None,HVH
3,\phs001013\pht005310\phv00259374\SAMPLE_USE\,phv00259374,SAMPLE_USE,Sample Use,Categorical,phs001013,[SNP genotypes obtained using standard or cust...,NaN,NaN,False,None,HVH
4,\phs001013\pht005312\phv00259397\SAMPLE_ID\,phv00259397,SAMPLE_ID,De-identified Sample ID,Categorical,phs001013,"[S10001, S10002, S10003, S10004, S10005, S1000...",NaN,NaN,False,None,HVH
...,...,...,...,...,...,...,...,...,...,...,...,...
1710,\phs000335\pht003965\phv00202525\SAMPID\,phv00202525,SAMPID,De-identified sample ID,Continuous,phs000335,[],100054.0,599908.0,False,None,HF_Collection_LHS
1711,\phs000335\pht002116\phv00154556\sample2\,phv00154556,sample2,Second sample ID of cryptic relatedness,Continuous,phs000335,[],132172.0,439664.0,False,None,HF_Collection_LHS
1712,\phs000335\pht002115\phv00154552\SAMPID\,phv00154552,SAMPID,Sample genotyping instance ID,Continuous,phs000335,[],100054.0,599908.0,False,None,HF_Collection_LHS
1713,\phs001515\pht009565\phv00420403\SAMPLE_ID\,phv00420403,SAMPLE_ID,Sample ID,Categorical,phs001515,"[NWD100011, NWD100067, NWD100262, NWD100285, N...",NaN,NaN,False,None,MLOF
1714,\phs001515\pht009567\phv00420412\SAMPLE_ID\,phv00420412,SAMPLE_ID,De-identified Sample ID,Categorical,phs001515,"[NWD100011, NWD100067, NWD100262, NWD100285, N...",NaN,NaN,False,None,MLOF

In [90]:
cryptic = session.searchDictionary("cryptic")
cryptic.to_csv('test.csv', index=False)

In [54]:
cocaine_list2 = cocaine.loc[cocaine['studyId'] == 'phs003463']['conceptPath']

with open('recover_cocaine.txt', 'w') as f:
    for line in cocaine_list2:
        f.write(f"{line}\n")

In [38]:
newid

,conceptPath,name,display,description,dataType,studyId,values,min,max,allowFiltering,meta,studyAcronym
0,\phs003740\NEWID\,NEWID,NEWID,NEWID,Continuous,phs003740,[],5.0,3873.0,True,None,BioLINCC_JHS
1,\phs004275\NEWID\,NEWID,NEWID,NEWID,Continuous,phs004275,[],75364.0,96697.0,True,None,BioLINCC_PPH-Registry
2,\phs004550\NEWID\,NEWID,NEWID,NEWID,Continuous,phs004550,[],1.0,3339.0,True,None,BioLINCC_TIMI_II
3,\phs004541\newid\,newid,newid,newid,Continuous,phs004541,[],3201.0,3831.0,True,None,BioLINCC_MASM
4,\phs004495\NEWID\,NEWID,NEWID,NEWID,Continuous,phs004495,[],1.0,663.0,True,None,BioLINCC_DISC
5,\phs004661\NEWID\,NEWID,NEWID,NEWID,Continuous,phs004661,[],1001.0,4915.0,True,None,BioLINCC_ACT
6,\phs004643\NEWID\,NEWID,NEWID,NEWID,Continuous,phs004643,[],1.0,1351.0,True,None,BioLINCC_CABG
7,\phs004647\newID\,newID,newID,newID,Continuous,phs004647,[],512537.0,514635.0,True,None,BioLINCC_CASS
8,\phs004639\newID\,newID,newID,newID,Continuous,phs004639,[],313217.0,317276.0,True,None,BioLINCC_AFFIRM
9,\phs004676\NEWID\,NEWID,NEWID,NEWID,Categorical,phs004676,"[XX001520, XX001651, XX002134, XX003765, XX003...",NaN,NaN,True,None,BioLINCC_CPAP
10,\phs004591\newid\,newid,newid,newid,Categorical,phs004591,"[IPF0001, IPF0002, IPF0003, IPF0004, IPF0005, ...",NaN,NaN,True,None,BioLINCC_IPF_Survival_PR
11,\phs004322\newID\,newID,newID,newID,Continuous,phs004322,[],1010425.0,9935812.0,True,None,BioLINCC_P2C2
12,\phs004554\NEWID\,NEWID,NEWID,NEWID,Continuous,phs004554,[],1.0,663.0,True,None,BioLINCC_DISC06
13,\phs004010\NEWID\,NEWID,NEWID,null,Categorical,phs004010,"[1, 10, 100, 1000, 1001, 1002, 1003, 1004, 100...",NaN,NaN,True,None,BioLINCC_IPPB
14,\phs003930\NEWID\,NEWID,NEWID,null,Categorical,phs003930,"[10002033, 100026152, 100055517, 100116586, 10...",NaN,NaN,True,None,BioLINCC_PRHHP
15,\phs003740\subjects\subject_id\NEWID\,,,,Continuous,phs003740,[],1.0,3883.0,True,None,BioLINCC_JHS
16,\phs003599\NEWID\,NEWID,Randomized participant ID,Randomized participant ID,Categorical,phs003599,"[HFACT00001, HFACT00002, HFACT00003, HFACT0000...",NaN,NaN,False,None,BioLINCC_HF-ACTION
17,\phs003599\subjects\subject_id\NEWID\,subject_id,NEWID,,Categorical,phs003599,"[HFACT00001, HFACT00002, HFACT00003, HFACT0000...",NaN,NaN,False,None,BioLINCC_HF-ACTION
18,\phs004022\newid\,newid,BioLINCC participant ID,BioLINCC participant ID,Categorical,phs004022,"[XX0003000, XX0003863, XX0015093, XX0018506, X...",NaN,NaN,False,None,BioLINCC_BEST_COPD
19,\phs004173\newid\,newid,newid,Random Participant ID,Continuous,phs004173,[],1.0,11816.0,False,None,BioLINCC_BHS
20,\phs004203\newid\,newid,newid,Random ID,Categorical,phs004203,"[IDN00128, IDN00132, IDN00213, IDN00221, IDN00...",NaN,NaN,False,None,BioLINCC_SCDIC
21,\phs004183\NEWID\,NEWID,NEWID,Patient ID,Continuous,phs004183,[],1.0,196.0,False,None,BioLINCC_PIMI
22,\phs004276\NEWID\,NEWID,Patient ID,Patient ID,Continuous,phs004276,[],1.1,736.2,False,None,BioLINCC_ACCESS
23,\phs004187\newID\,newID,"Patient Registry ID, scrmbld","Patient Registry ID, scrmbld",Continuous,phs004187,[],18105.0,9940104.0,False,None,BioLINCC_AADR
24,\phs004674\allcdp_shared\newid\,newid,Masked Participant ID Number,( allcdp_shared ) - Masked Participant ID Number,Categorical,phs004674,"[CDP0001, CDP0002, CDP0003, CDP0004, CDP0005, ...",NaN,NaN,False,None,BioLINCC_CDP

In [44]:
newid_list = newid.loc[newid['allowFiltering'] == True]['conceptPath'].tolist()
new_id_list = new_id.loc[new_id['allowFiltering'] == True]['conceptPath'].tolist()
sampid_list = sampid.loc[sampid['allowFiltering'] == True]['conceptPath'].tolist()
samp_id_list = samp_id.loc[samp_id['allowFiltering'] == True]['conceptPath'].tolist()
randid_list = randid.loc[randid['allowFiltering'] == True]['conceptPath'].tolist()
rand_id_list = rand_id.loc[rand_id['allowFiltering'] == True]['conceptPath'].tolist()
marriage_list = marriage.loc[marriage['allowFiltering'] == True]['conceptPath'].tolist()
herpesvirus_list = herpesvirus.loc[herpesvirus['allowFiltering'] == True]['conceptPath'].tolist()
cocaine_list = cocaine.loc[cocaine['allowFiltering'] == True]['conceptPath'].tolist()

In [45]:
full_list = new_id_list + newid_list + samp_id_list + sampid_list + rand_id_list + randid_list + marriage_list + herpesvirus_list + cocaine_list

In [46]:
with open('QA_concepts.txt', 'w') as f:
    for line in full_list:
        f.write(f"{line}\n")